### ISSUE TITLE
Import: issue edits and comment edits incorrect

### ISSUE THREAD

**Issue by rng-dynamics** [MichaelMure/git-bug#629]
I am importing the issues from https://github.com/rng-dynamics/gb-test-two.

When I use git-bug from the current master branch (bc5f618e), then the import is not correct: The issue https://github.com/rng-dynamics/gb-test-two/issues/2 is missing issue edits and comment edits:

```
 [open] Alexander Scharinger opened this bug on Apr 9 2021

     comment 1


 Alexander Scharinger commented on Apr 9 2021

     comment 3
```

Some time ago it used to work. E.g., on 01b9490 the import is correct:
```
 [open] Alexander Scharinger opened this bug on Apr 9 2021 (edited)

     comment 1, edit 2


 Alexander Scharinger commented on Apr 9 2021 (edited)

     comment 3, edit 4
```

**Comment by MichaelMure** [comment]
Is this fixed in your now merged branch?

**Comment by rng-dynamics** [comment]
To me it seems that the error is not in the github bridge but somewhere else. So, no, it's not fixed. It has been introduced somewhere between 01b9490 and bc5f618. I tried to bisect it, but was not successful in locating it yet.

**Comment by rng-dynamics** [comment]
I think I found the problem. I will send you a PR soon.
